export type KeybindGroup = {
  title: string
  fields: Array<{ key: string; label: string; placeholder?: string }>
}

export const MODALITIES = ['text', 'audio', 'image', 'video', 'pdf']

export const PROVIDER_OPTION_KEYS = [
  'apiKey',
  'baseURL',
  'enterpriseUrl',
  'setCacheKey',
  'timeout',
  'headers',
  'includeUsage',
  'useCompletionUrls',
  'region',
  'profile',
  'endpoint',
  'project',
  'location',
  'deploymentId',
  'resourceGroup',
  'instanceUrl',
  'featureFlags',
]

export const BUILTIN_LSP_IDS = new Set([
  'deno',
  'typescript',
  'vue',
  'eslint',
  'oxlint',
  'biome',
  'gopls',
  'ruby-lsp',
  'ty',
  'pyright',
  'elixir-ls',
  'zls',
  'csharp',
  'fsharp',
  'sourcekit-lsp',
  'rust',
  'clangd',
  'svelte',
  'astro',
  'jdtls',
  'kotlin-ls',
  'yaml-ls',
  'lua-ls',
  'php intelephense',
  'prisma',
  'dart',
  'ocaml-lsp',
  'bash',
  'terraform',
  'texlab',
  'dockerfile',
  'gleam',
  'clojure-lsp',
  'nixd',
  'tinymist',
  'haskell-language-server',
])

export const KEYBIND_GROUPS: KeybindGroup[] = [
  {
    title: 'App & UI',
    fields: [
      { key: 'leader', label: 'Leader', placeholder: 'ctrl+x' },
      { key: 'app_exit', label: 'App exit', placeholder: 'ctrl+c,ctrl+d,<leader>q' },
      { key: 'editor_open', label: 'Editor open', placeholder: '<leader>e' },
      { key: 'theme_list', label: 'Theme list', placeholder: '<leader>t' },
      { key: 'sidebar_toggle', label: 'Sidebar toggle', placeholder: '<leader>b' },
      { key: 'scrollbar_toggle', label: 'Scrollbar toggle', placeholder: 'none' },
      { key: 'username_toggle', label: 'Username toggle', placeholder: 'none' },
      { key: 'status_view', label: 'Status view', placeholder: '<leader>s' },
      { key: 'tool_details', label: 'Tool details', placeholder: 'none' },
      { key: 'tips_toggle', label: 'Tips toggle', placeholder: '<leader>h' },
      { key: 'display_thinking', label: 'Display thinking', placeholder: 'none' },
      { key: 'terminal_title_toggle', label: 'Terminal title toggle', placeholder: 'none' },
      { key: 'terminal_suspend', label: 'Terminal suspend', placeholder: 'ctrl+z' },
    ],
  },
  {
    title: 'Sessions',
    fields: [
      { key: 'session_export', label: 'Session export', placeholder: '<leader>x' },
      { key: 'session_new', label: 'Session new', placeholder: '<leader>n' },
      { key: 'session_list', label: 'Session list', placeholder: '<leader>l' },
      { key: 'session_timeline', label: 'Session timeline', placeholder: '<leader>g' },
      { key: 'session_fork', label: 'Session fork', placeholder: 'none' },
      { key: 'session_rename', label: 'Session rename', placeholder: 'ctrl+r' },
      { key: 'session_delete', label: 'Session delete', placeholder: 'ctrl+d' },
      { key: 'stash_delete', label: 'Stash delete', placeholder: 'ctrl+d' },
      { key: 'session_share', label: 'Session share', placeholder: 'none' },
      { key: 'session_unshare', label: 'Session unshare', placeholder: 'none' },
      { key: 'session_interrupt', label: 'Session interrupt', placeholder: 'escape' },
      { key: 'session_compact', label: 'Session compact', placeholder: '<leader>c' },
      { key: 'session_child_cycle', label: 'Session child cycle', placeholder: '<leader>right' },
      { key: 'session_child_cycle_reverse', label: 'Session child cycle reverse', placeholder: '<leader>left' },
      { key: 'session_parent', label: 'Session parent', placeholder: '<leader>up' },
    ],
  },
  {
    title: 'Messages',
    fields: [
      { key: 'messages_page_up', label: 'Messages page up', placeholder: 'pageup,ctrl+alt+b' },
      { key: 'messages_page_down', label: 'Messages page down', placeholder: 'pagedown,ctrl+alt+f' },
      { key: 'messages_line_up', label: 'Messages line up', placeholder: 'ctrl+alt+y' },
      { key: 'messages_line_down', label: 'Messages line down', placeholder: 'ctrl+alt+e' },
      { key: 'messages_half_page_up', label: 'Messages half page up', placeholder: 'ctrl+alt+u' },
      { key: 'messages_half_page_down', label: 'Messages half page down', placeholder: 'ctrl+alt+d' },
      { key: 'messages_first', label: 'Messages first', placeholder: 'ctrl+g,home' },
      { key: 'messages_last', label: 'Messages last', placeholder: 'ctrl+alt+g,end' },
      { key: 'messages_next', label: 'Messages next', placeholder: 'none' },
      { key: 'messages_previous', label: 'Messages previous', placeholder: 'none' },
      { key: 'messages_last_user', label: 'Messages last user', placeholder: 'none' },
      { key: 'messages_copy', label: 'Messages copy', placeholder: '<leader>y' },
      { key: 'messages_undo', label: 'Messages undo', placeholder: '<leader>u' },
      { key: 'messages_redo', label: 'Messages redo', placeholder: '<leader>r' },
      { key: 'messages_toggle_conceal', label: 'Messages toggle conceal', placeholder: '<leader>h' },
    ],
  },
  {
    title: 'Models & Agents',
    fields: [
      { key: 'model_provider_list', label: 'Model provider list', placeholder: 'ctrl+a' },
      { key: 'model_favorite_toggle', label: 'Model favorite toggle', placeholder: 'ctrl+f' },
      { key: 'model_list', label: 'Model list', placeholder: '<leader>m' },
      { key: 'model_cycle_recent', label: 'Model cycle recent', placeholder: 'f2' },
      { key: 'model_cycle_recent_reverse', label: 'Model cycle recent reverse', placeholder: 'shift+f2' },
      { key: 'model_cycle_favorite', label: 'Model cycle favorite', placeholder: 'none' },
      { key: 'model_cycle_favorite_reverse', label: 'Model cycle favorite reverse', placeholder: 'none' },
      { key: 'command_list', label: 'Command list', placeholder: 'ctrl+p' },
      { key: 'agent_list', label: 'Agent list', placeholder: '<leader>a' },
      { key: 'agent_cycle', label: 'Agent cycle', placeholder: 'tab' },
      { key: 'agent_cycle_reverse', label: 'Agent cycle reverse', placeholder: 'shift+tab' },
      { key: 'variant_cycle', label: 'Variant cycle', placeholder: 'ctrl+t' },
    ],
  },
  {
    title: 'Input',
    fields: [
      { key: 'input_clear', label: 'Input clear', placeholder: 'ctrl+c' },
      { key: 'input_paste', label: 'Input paste', placeholder: 'ctrl+v' },
      { key: 'input_submit', label: 'Input submit', placeholder: 'return' },
      { key: 'input_newline', label: 'Input newline', placeholder: 'shift+return,ctrl+return,alt+return,ctrl+j' },
      { key: 'input_move_left', label: 'Input move left', placeholder: 'left,ctrl+b' },
      { key: 'input_move_right', label: 'Input move right', placeholder: 'right,ctrl+f' },
      { key: 'input_move_up', label: 'Input move up', placeholder: 'up' },
      { key: 'input_move_down', label: 'Input move down', placeholder: 'down' },
      { key: 'input_select_left', label: 'Input select left', placeholder: 'shift+left' },
      { key: 'input_select_right', label: 'Input select right', placeholder: 'shift+right' },
      { key: 'input_select_up', label: 'Input select up', placeholder: 'shift+up' },
      { key: 'input_select_down', label: 'Input select down', placeholder: 'shift+down' },
      { key: 'input_line_home', label: 'Input line home', placeholder: 'ctrl+a' },
      { key: 'input_line_end', label: 'Input line end', placeholder: 'ctrl+e' },
      { key: 'input_select_line_home', label: 'Input select line home', placeholder: 'ctrl+shift+a' },
      { key: 'input_select_line_end', label: 'Input select line end', placeholder: 'ctrl+shift+e' },
      { key: 'input_visual_line_home', label: 'Input visual line home', placeholder: 'alt+a' },
      { key: 'input_visual_line_end', label: 'Input visual line end', placeholder: 'alt+e' },
      { key: 'input_select_visual_line_home', label: 'Input select visual line home', placeholder: 'alt+shift+a' },
      { key: 'input_select_visual_line_end', label: 'Input select visual line end', placeholder: 'alt+shift+e' },
      { key: 'input_buffer_home', label: 'Input buffer home', placeholder: 'home' },
      { key: 'input_buffer_end', label: 'Input buffer end', placeholder: 'end' },
      { key: 'input_select_buffer_home', label: 'Input select buffer home', placeholder: 'shift+home' },
      { key: 'input_select_buffer_end', label: 'Input select buffer end', placeholder: 'shift+end' },
      { key: 'input_delete_line', label: 'Input delete line', placeholder: 'ctrl+shift+d' },
      { key: 'input_delete_to_line_end', label: 'Input delete to line end', placeholder: 'ctrl+k' },
      { key: 'input_delete_to_line_start', label: 'Input delete to line start', placeholder: 'ctrl+u' },
      { key: 'input_backspace', label: 'Input backspace', placeholder: 'backspace,shift+backspace' },
      { key: 'input_delete', label: 'Input delete', placeholder: 'ctrl+d,delete,shift+delete' },
      { key: 'input_undo', label: 'Input undo', placeholder: 'ctrl+-,super+z' },
      { key: 'input_redo', label: 'Input redo', placeholder: 'ctrl+.,super+shift+z' },
      { key: 'input_word_forward', label: 'Input word forward', placeholder: 'alt+f,alt+right,ctrl+right' },
      { key: 'input_word_backward', label: 'Input word backward', placeholder: 'alt+b,alt+left,ctrl+left' },
      {
        key: 'input_select_word_forward',
        label: 'Input select word forward',
        placeholder: 'alt+shift+f,alt+shift+right',
      },
      {
        key: 'input_select_word_backward',
        label: 'Input select word backward',
        placeholder: 'alt+shift+b,alt+shift+left',
      },
      {
        key: 'input_delete_word_forward',
        label: 'Input delete word forward',
        placeholder: 'alt+d,alt+delete,ctrl+delete',
      },
      {
        key: 'input_delete_word_backward',
        label: 'Input delete word backward',
        placeholder: 'ctrl+w,ctrl+backspace,alt+backspace',
      },
    ],
  },
  {
    title: 'History',
    fields: [
      { key: 'history_previous', label: 'History previous', placeholder: 'up' },
      { key: 'history_next', label: 'History next', placeholder: 'down' },
    ],
  },
]

export const PROMPT_SKELETON = `# Goal\n\n# Context\n\n# Instructions\n\n# Output\n`
export const FRONTMATTER_SKELETON = `---\n# title: \n# tags: []\n---\n\n`
